AMI_SERVER = "ami-027583e616ca104df"
KEY_PEM = ""
INSTANCE_TYPE_MICRO = "t2.micro"
INSTANCE_TYPE_SMALL = "t2.small"
INSTANCE_TYPE_LARGE_MEM = "m4.large"
INSTANCE_TYPE_LARGE_DISK = "i3.large"
INSTANCE_TYPE_MEDIUM_T = 't2.medium'
INSTANCE_TYPE_XLARGE = 'm4.xlarge'

RELEASE_LABEL_EMR = "emr-5.24.0"

MIN_KAFKA_CLUSTER_SIZE = 1
DESIRED_KAFKA_CLUSTER_SIZE = 1
MAX_KAFKA_CLUSTER_SIZE = 1

SERVICE_LAUNCH_CONFIGURATION = "service_launch_configuration"
SERVER_LAUNCH_CONFIGURATION = "server_launch_configuration"

ACCESS_KEY_ID = ''
ACCESS_SECRET_KEY = ''
