version: '3.3'


services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2182:2181"
  kafka:
    build: .
    container_name: broker
    hostname: broker
    ports:
      - "9092:9092"
    networks:
      default:
        ipv4_address: 10.0.0.10
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.0.10:9092
      KAFKA_LISTENERS: PLAINTEXT://10.0.0.10:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.0.0.10:9092
      KAFKA_CREATE_TOPICS: "comments:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181



networks:
  default:
    external:
      name: dspnet
